---
  - a remote siberian plateau
  - a small frontier town
  - an abandoned mining village in China
  - a luxury villa in the shadow of a dormant volcano
  - a skyscraper in midtown Manhattan
  - an experimental architecture school
  - a sleepy village on the Great Lakes